Traceback (most recent call last):
  File "/nas/longleaf/home/cyixiao/Project/Cheshire/main.py", line 35, in <module>
    main()
  File "/nas/longleaf/home/cyixiao/Project/Cheshire/main.py", line 16, in main
    auc, f1, accuracy = get_prediction_score(name=args.name, args=args)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_prediction_score() got an unexpected keyword argument 'args'
